name: Deploy Next.js site to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Use the Node.js version your project requires

      - name: Install dependencies
        run: npm install

      - name: Build Next.js site
        run: npm run build && npm run export

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: next
          token: ${{ secrets.GITHUB_TOKEN }}
          enablement: true  # Ensure enablement is set to true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out  # The directory where the exported site is located
